from car import Car
Car1 = Car("Mustang", 2026, "Red", False)
print(Car1.model) 
print(Car1.year)
print(Car1.color)
print(Car1.for_sale)
print()
Car2 = Car("Corvette", 2025, "blue", True)
print(Car2.model) 
print(Car2.year)
print(Car2.color)
print(Car2.for_sale)
print()
Car1.drive()
Car1.stop()